apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: default
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 80        # External port (ingress uses this)
      targetPort: 8080 # Internal port (app uses this)
  type: ClusterIP
